# Generated by Django 4.0.4 on 2023-06-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance__django', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
